version: '3'

services:
  app:
    build: ./app
    image: kry667/restful:project101-app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"  # Expose the Flask app on port 5000
    networks:
      - my-network1
    depends_on:
      - user_crud
      - employee_crud  # Add dependency on employee_crud

  user_crud:
    build: ./user_crud
    image: kry667/restful:project101-user_crud
    volumes:
      - ./user_crud:/user_crud
    ports:
      - "5001:5000"  # Expose the user CRUD API on port 5001
    networks:
      - my-network1
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

  employee_crud:  # Add the employee_crud service
    build: ./employee_crud
    image: kry667/restful:project101-employee_crud
    volumes:
      - ./employee_crud:/employee_crud
    ports:
      - "5002:5000"  # Expose the employee CRUD API on port 5002
    networks:
      - my-network1
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

  db:
    build: ./db
    image: kry667/restful:users_employees_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_HOST=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    networks:
      - my-network1
    volumes:
      - db-data:/var/lib/mysql

networks:
  my-network1:
    external: true

volumes:
  db-data:
