version: '3'

services:
  app:
    build: ./app
    image: kry667/restful:project101-app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - my-network1
    depends_on:
      - user_crud
      - employee_crud

  user_crud:
    build: ./user_crud
    image: kry667/restful:project101-user_crud
    volumes:
      - ./user_crud:/user_crud
    ports:
      - "5001:5000"
    networks:
      - my-network1
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

  employee_crud:
    build: ./employee_crud
    image: kry667/restful:project101-employee_crud
    volumes:
      - ./employee_crud:/employee_crud
    ports:
      - "5002:5000"
    networks:
      - my-network1
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}

  auth:
    build: ./auth
    image: kry667/restful:project101-auth
    volumes:
      - ./auth:/auth
    ports:
      - "5003:5000"
    networks:
      - my-network1
    depends_on:
      - user_crud
      - employee_crud
      - app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  db:
    build: ./db
    
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    networks:
      - my-network1
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    networks:
      - my-network1
    ports:
      - "6379:6379"


networks:
  my-network1:
    external: true

volumes:
  db-data:
