name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2

    - name: Build and push the app service image
      run: |
        docker build -t kry667/restful:project101-app ./app
        docker push kry667/restful:project101-app

    - name: Build and push the user_crud service image
      run: |
        docker build -t kry667/restful:project101-user_crud ./user_crud
        docker push kry667/restful:project101-user_crud

    - name: Build and push the employee_crud service image
      run: |
        docker build -t kry667/restful:project101-employee_crud ./employee_crud
        docker push kry667/restful:project101-employee_crud

    - name: Build and push the db service image
      run: |
        docker build -t kry667/restful:users_employees_db ./db
        docker push kry667/restful:users_employees_db
